In [7]:
#tabulate

from tabulate import tabulate

In [3]:
data = [['abc',50,100],['ccc',70,100],['bbb',60,100]]

In [4]:
print(data)

[['abc', 50, 100], ['ccc', 70, 100], ['bbb', 60, 100]]


In [8]:
print(tabulate(data))

---  --  ---
abc  50  100
ccc  70  100
bbb  60  100
---  --  ---


In [9]:
print(tabulate(data,headers =['name','rollno','marks']))

name      rollno    marks
------  --------  -------
abc           50      100
ccc           70      100
bbb           60      100


In [11]:
d1 = {'name':['alice','bob'], 'age':[30,70], 'rollno':[1001,1002]}
print(d1)

{'name': ['alice', 'bob'], 'age': [30, 70], 'rollno': [1001, 1002]}


In [15]:
print(tabulate(d1,headers ='keys'))

name      age    rollno
------  -----  --------
alice      30      1001
bob        70      1002


In [19]:
print(tabulate(d1,headers = 'firstrow', showindex = 'always', tablefmt = 'html')) #html

<table>
<thead>
<tr><th style="text-align: right;">  </th><th>alice  </th><th style="text-align: right;">  30</th><th style="text-align: right;">  1001</th></tr>
</thead>
<tbody>
<tr><td style="text-align: right;"> 0</td><td>bob    </td><td style="text-align: right;">  70</td><td style="text-align: right;">  1002</td></tr>
</tbody>
</table>


In [22]:
print(tabulate(d1,headers = 'firstrow', showindex = 'always', tablefmt = 'fancy_grid'))

╒════╤═════════╤══════╤════════╕
│    │ alice   │   30 │   1001 │
╞════╪═════════╪══════╪════════╡
│  0 │ bob     │   70 │   1002 │
╘════╧═════════╧══════╧════════╛


In [23]:
import numpy as np
x1=np.random.randint(1,2000, size = (20,1))
x2=np.random.randint(1,2000, size = (20,1))
x3=np.random.randint(1,2000, size = (20,1))

x1

array([[1964],
       [1988],
       [1470],
       [1413],
       [ 313],
       [ 356],
       [1909],
       [ 154],
       [ 764],
       [1533],
       [ 548],
       [ 350],
       [ 290],
       [1590],
       [1925],
       [ 408],
       [1608],
       [1230],
       [ 493],
       [ 483]])

In [27]:
X = np.concatenate((x1,x2,x3), axis = 1)
X

array([[1964, 1083,  858],
       [1988, 1858, 1922],
       [1470,  796, 1829],
       [1413, 1520,  788],
       [ 313, 1935,  606],
       [ 356, 1050, 1221],
       [1909,  986,  486],
       [ 154,  175,  827],
       [ 764, 1558, 1908],
       [1533, 1212,  624],
       [ 548, 1396, 1747],
       [ 350,   68, 1811],
       [ 290, 1307,  143],
       [1590,  518, 1837],
       [1925,  303, 1114],
       [ 408, 1123,  197],
       [1608,  703, 1022],
       [1230,  449, 1938],
       [ 493, 1949,  869],
       [ 483,  109,   23]])

In [ ]:
plt.plo(x1, '')

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
MMS = MinMaxScaler()

In [31]:
X_mms = MMS.fit_transform(X)
X_mms

array([[0.98691385, 0.53960659, 0.43603133],
       [1.        , 0.95162148, 0.99164491],
       [0.71755725, 0.38702818, 0.94308094],
       [0.68647764, 0.77192982, 0.39947781],
       [0.08669575, 0.99255715, 0.30443864],
       [0.11014177, 0.52206273, 0.62558747],
       [0.95692475, 0.48803828, 0.24177546],
       [0.        , 0.05688464, 0.41984334],
       [0.33260632, 0.79213184, 0.9843342 ],
       [0.7519084 , 0.60818713, 0.31383812],
       [0.21483097, 0.70600744, 0.9002611 ],
       [0.10687023, 0.        , 0.93368146],
       [0.07415485, 0.65869219, 0.06266319],
       [0.782988  , 0.23923445, 0.94725849],
       [0.96564885, 0.12493355, 0.56971279],
       [0.13849509, 0.56087188, 0.09086162],
       [0.79280262, 0.33758639, 0.52167102],
       [0.58669575, 0.20255183, 1.        ],
       [0.18484188, 1.        , 0.44177546],
       [0.17938931, 0.02179692, 0.        ]])

In [33]:
X_mms.std(axis = 0)

array([0.3589233 , 0.31243703, 0.33171398])